class EnumDef {
	public constructor() {
	}
}

//FightModule
enum FightModuleEnum {
	FIGHT_TYPE_PVE_NORMAL = 0,
	FIGHT_TYPE_PVE_ELIT = 1,
	FIGHT_TYPE_PVE_MONEY_TREE = 2,
	FIGHT_TYPE_PVE_TREASURE_EXPERIENCE = 3,
	FIGHT_TYPE_PVE_PANDA_EXPERIENCE = 4,
	FIGHT_TYPE_PVE_WORLD_BOSS = 5,
	FIGHT_TYPE_TRANS_TOWER = 6,
	FIGHT_TYPE_PVP_COUNTERPART = 7,
	FIGHT_TYPE_PVP_BATTLEGROUND = 8,
	FIGHT_TYPE_GREAT_SOLDIER = 9,
	FIGHT_TYPE_PVP_GRAB = 10,
	FIGHT_TYPE_PVP_ARENA = 11,
	FIGHT_TYPE_PVP_DUEL = 12,
	FIGHT_TYPE_PVP_UNIO = 13,
	FIGHT_TYPE_PVP_RESOURCE_MINE = 14,
	FIGHT_TYPE_PVP_SPIRITE_PALACE = 15,
	FIGHT_TYPE_PVP_CROSS_SERVER = 16,
	FIGHT_TYPE_51 = 51,
	FIGHT_TYPE_52 = 52,
	FIGHT_TYPE_DAILY_INSTANCE = 101,
	FIGHT_TYPE_PVE_THREE_KING = 102,
	FIGHT_TYPE_PVE_MANOR = 103,
	FIGHT_TYPE_PVE_REBELARMY = 104,
	FIGHT_TYPE_GREAT_SOLDIER_B = 105,

}

//TalentConstant 天赋触发时机
enum TalentConstant_JUDGE_OPPORTUNITY {
	JUDGE_OPPORTUNITY_BY_ATTACK =  0,						
	JUDGE_OPPORTUNITY_ATTACK =  1,
	JUDGE_OPPORTUNITY_SELF_DEAD =  2,						//自身死亡时判断
	JUDGE_OPPORTUNITY_OPPONENT_DEAD =  3,
	JUDGE_OPPORTUNITY_EMAMY_ATTACK =  4,
	JUDGE_OPPORTUNITY_OWER_ATTACK =  5,
	JUDGE_OPPORTUNITY_BATTLE_ROUND_START =  6,				//每场战斗开启时判定
	JUDGE_OPPORTUNITY_CAMP_ROLE_DEATH =  7,					//友军阵亡时判定
	JUDGE_OPPORTUNITY_INIT_BATTLE_SCENE =  8,				//进入战斗时
	JUDGE_OPPORTUNITY_ATTACK_ROUND_START =  9,				//回合开始时判定
	JUDGE_OPPORTUNITY_ATTACK_BEFORE =  10,					//出手前判定
	JUDGE_OPPORTUNITY_OPPONENT_DEAD_GLOBAL =  11,			//敌方死亡的全局天赋
	JUDGE_OPPORTUNITY_OPPONENT_FOR_ATTACK_BEFORE =  12,		//发动攻击前
}
